//
//  UIColor+HTWColors.m
//
//  Generated by Zeplin on 8/24/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import "UIColor+HTWColors.h"

@implementation UIColor (HTWColors)

+ (UIColor *)htw_duskBlueColor {
    return [UIColor colorWithRed:66.0f / 255.0f green:74.0f / 255.0f blue:98.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)htw_squashColor {
    return [UIColor colorWithRed:245.0f / 255.0f green:166.0f / 255.0f blue:35.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)htw_dodgerBlueColor {
    return [UIColor colorWithRed:68.0f / 255.0f green:154.0f / 255.0f blue:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)htw_paleLimeGreenColor {
    return [UIColor colorWithRed:170.0f / 255.0f green:255.0f / 255.0f blue:84.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)htw_whiteColor {
    return [UIColor colorWithWhite:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)htw_aquaMarineColor {
    return [UIColor colorWithRed:80.0f / 255.0f green:227.0f / 255.0f blue:194.0f / 255.0f alpha:1.0f];
}

@end
