//
//  UIColor+HTWColors.h
//
//  Generated by Zeplin on 8/24/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface UIColor (HTWColors)

+ (UIColor *)htw_duskBlueColor;
+ (UIColor *)htw_squashColor;
+ (UIColor *)htw_dodgerBlueColor;
+ (UIColor *)htw_paleLimeGreenColor;
+ (UIColor *)htw_whiteColor;
+ (UIColor *)htw_aquaMarineColor;

@end
